using DL_Turbo_Free.Models;
using System.IO;
using System.Reflection;
using System.Text;

namespace DL_Turbo_Free.Helper
{
    internal class SrtToAss
    {
        public static void ConvertSrtToAss(string outputPath, List<SubtitleItem> lines)
        {
            StringBuilder assLine = new();

            string assHeader = GenerateAssHeader(Path.GetFileName(outputPath));
            foreach (var line in lines)
            {
                assLine.AppendLine(string.Format("Dialogue: 0,{0},{1},Default,{2},0,0,0,,{3}",
                    FormatTimeForAss(line.StartTime),
                    FormatTimeForAss(line.EndTime),
                    string.IsNullOrEmpty(line.Actor) ? "N/A" : line.Actor,
                    EscapeAssText(line.Text)));
            }
            
            File.WriteAllText(outputPath, assHeader + assLine.ToString(), Encoding.UTF8);
        }


        private static string EscapeAssText(string text)
        {
            if (string.IsNullOrEmpty(text))
                return string.Empty;
            return text.Replace(@"\", @"\\").Replace("{", @"\{").Replace("}", @"\}").Replace("\n", @"\N");
        }

        private static string FormatTimeForAss(string time)
        {
            if (!TimeSpan.TryParse(time, out TimeSpan timeSpan))
                return "0:00:00.00";
            return string.Format("{0}:{1:D2}:{2:D2}.{3:D2}", (int)timeSpan.TotalHours, timeSpan.Minutes, timeSpan.Seconds, timeSpan.Milliseconds / 10);
        }

        private static string GenerateAssHeader(string outputFileName)
        {
            StringBuilder header = new();

            header.AppendLine("[Script Info]");
            header.AppendLine($"; Script generated by DL Turbo Free\r\n; https://vk.com/aatonoyan\r\n; Author: Artur Tonoyan\r\n; App version: {Assembly.GetExecutingAssembly().GetName().Version?.ToString()}");
            header.AppendLine($"Title: Converted Subtitle: {outputFileName}");
            header.AppendLine("ScriptType: v4.00+");
            header.AppendLine("WrapStyle: 0");
            header.AppendLine("ScaledBorderAndShadow: yes");
            header.AppendLine("YCbCr Matrix: None");
            header.AppendLine();
            header.AppendLine("[V4+ Styles]");
            header.AppendLine("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding");
            header.AppendLine("Style: Default,Arial,20,&H00FFFFFF,&H0000FFFF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1");
            header.AppendLine();
            header.AppendLine("[Events]");
            header.AppendLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");
            return header.ToString();
        }
    }
}